version: "3.7"
services:
  rstudio:
    container_name: rocker_bis
    image: rocker/ml-verse
    # build :
    #  context: .
    #  dockerfile: ./rstudio.dockerfile
    # volumes: 
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - USERNAME=rstudio
      - PASSWORD=rstudio1234
      - TZ=Asia/Tokyo
    ports:
      - 7188:8787
    #volumes:
    #  -
    working_dir: /work
    tty: true
    restart: always
